version: 2.1
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3.3-fpm-node
      - image: circleci/mysql:8.0-ram
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing_db
    steps:
      - checkout
      - run:
          name: Install required libraries and extensions
          command: |
            cp .env.testing .env && sudo apt update && sudo apt install -y zlib1g-dev \
            libsqlite3-dev \
            docker-php-ext-install \
            zip \
            docker-php-ext-install \
            pdo \
            pdo_mysql \
            mysql-client

      # composer cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Prepare the database and Run tests
          command: |
            composer dump-autoload &&
            php artisan key:generate &&
            php artisan migrate --force &&
            php artisan db:seed --force &&
            ./vendor/phpunit/phpunit/phpunit
